on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send repo to Dataverse 
        uses: IQSS/dataverse-uploader@v1.4
        with:
          DATAVERSE_TOKEN: a8cd1dc6-a857-49cd-884a-d82445c49e3c
          DATAVERSE_SERVER: https://researchdata.cuhk.edu.hk
          DATAVERSE_DATASET_DOI: doi:10.48668/RINCZR
